### ISSUE TITLE
SimOTA

### ISSUE THREAD

**Issue by ddz16** [TuanTNG/TemporalMaxer#3]
Very simple but effective model! Howerver, I notice you use SimOTA in your code, but Actionformer does not use it.  So I want to know if SimOTA can bring some performance improvement.

**Comment by TuanTNG** [comment]
Hi,

We appreciate your interest.
Initially, we wanted to determine whether SimOTA could enhance the performance of TemporalMaxer.
Unfortunately, it did not yield any performance improvements.
Nevertheless, due to our busy schedule, we have decided to keep SimOTA in place without further modifications.
